name: Pull Request

on: pull_request

jobs:
  pull-request:
    name: Check PR source
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Node
        uses: actions/setup-node@v3.5.0
        with:
          check-latest: true
      - name: Check dependencies
        run: yarn --immutable --immutable-cache --check-cache
      - name: Run tests
        run: yarn test
