name: Release Docs

on:
  push:
    branches:
      - main
    paths:
      - packages/trakas-docs/**

jobs:
  release:
    name: GitHub Pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Node
        uses: actions/setup-node@v3.4.0
        with:
          check-latest: true
      - name: Check dependencies
        run: yarn --immutable --immutable-cache
      - name: Release
        env:
          ALGOLIA_APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          ALGOLIA_API_KEY: ${{ secrets.ALGOLIA_SEARCH_API_KEY }}
          DEPLOYMENT_BRANCH: main
          GIT_USER: actions
          GIT_PASS: ${{ secrets.GH_TOKEN }}
        run: |
          git config --global user.name "actions"
          git config --global user.email "actions@github.com"
          yarn publish:docs
      - name: Crawl docs to DocSearch
        working-directory: packages/trakas-docs
        env:
          APPLICATION_ID: ${{ secrets.ALGOLIA_APPLICATION_ID }}
          API_KEY: ${{ secrets.ALGOLIA_ADMIN_API_KEY }}
        run: docker run -t -e APPLICATION_ID=$APPLICATION_ID -e API_KEY=$API_KEY -e "CONFIG=$(cat docsearch.config.json)" algolia/docsearch-scraper
