name: Release

on:
  push:
    branches:
      - main
    paths-ignore:
      - packages/trakas-docs/**

jobs:
  yarn:
    name: Yarn
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Node
        uses: actions/setup-node@v2.4.0
        with:
          check-latest: true
      - name: Check dependencies
        run: yarn --immutable --immutable-cache
  tests:
    name: Tests
    runs-on: ubuntu-latest
    needs: [yarn]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Node
        uses: actions/setup-node@v2.4.0
        with:
          check-latest: true
      - name: Run tests
        run: |
          yarn
          yarn test
  eslint:
    name: ESLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Node
        uses: actions/setup-node@v2.4.0
        with:
          check-latest: true
      - name: Run Eslint check
        run: yarn eslint
  prettier:
    name: Prettier
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Node
        uses: actions/setup-node@v2.4.0
        with:
          check-latest: true
      - name: Run Prettier check
        run: yarn prettier
  deepcode:
    name: DeepCode
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Python
        uses: actions/setup-python@v2
      - name: Install DeepCode
        run: |
          python -m pip install --upgrade pip
          pip install deepcode
      - name: Analyze
        env:
          DEEPCODE_API_KEY: ${{ secrets.DEEPCODE_API_KEY }}
        run: deepcode analyze --path .
  release:
    name: NPM
    runs-on: ubuntu-latest
    needs: [tests, eslint, prettier, deepcode]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          fetch-depth: 0
      - name: Set up Node
        uses: actions/setup-node@v2.4.0
        with:
          check-latest: true
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: yarn publish
