name: Release Docs

on:
  push:
    branches:
      - main
    paths:
      - packages/trakas-docs/**

jobs:
  release:
    name: GitHub Pages
    runs-on: ubuntu-latest
    needs: [tests, eslint, prettier, deepcode]
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
      - name: Set up Node
        uses: actions/setup-node@v2.1.4
        with:
          check-latest: true
      - name: Check dependencies
        run: yarn --immutable --immutable-cache
      - name: Release
        env:
          DEPLOYMENT_BRANCH: main
          GIT_PASS: ${{ secrets.GITHUB_TOKEN }}
        run: yarn publish:docs
